// Package parser is used for parsing Espresso, a human friendly
// format based on a subset of CoffeeScript, as defined by spec [1].
//
// It is automatically generated by pigeon [2].
// Do not edit manually, make changes to PEG file instead.
//
// [1]: https://github.com/anonx/espresso
// [2]: https://github.com/PuerkitoBio/pigeon
package parser

import (
	"bytes"
	"errors"
	"fmt"
	"io"
	"io/ioutil"
	"os"
	"strconv"
	"strings"
	"unicode"
	"unicode/utf8"
)

// sliceOfKVSlicesToObject gets a value that must be [][]interface{}
// that has the following structure: [["key1", "value1"], ["key2", "value2"]].
// And returns it as map[interface{}]interface{}.
// It doesn't have any checks for purpose and will panic if input is incorrect.
func sliceOfKVSlicesToObject(val interface{}) (map[interface{}]interface{}, error) {
	lst := val.([]interface{})
	obj := make(map[interface{}]interface{}, len(lst))
	for i := 0; i < len(lst); i++ {
		t := lst[i].([]interface{})
		obj[t[0]] = t[1]
	}
	return obj, nil
}

var g = &grammar{
	rules: []*rule{
		{
			name: "Espresso",
			pos:  position{line: 43, col: 1, offset: 1105},
			expr: &actionExpr{
				pos: position{line: 43, col: 13, offset: 1117},
				run: (*parser).callonEspresso1,
				expr: &seqExpr{
					pos: position{line: 43, col: 13, offset: 1117},
					exprs: []interface{}{
						&ruleRefExpr{
							pos:  position{line: 43, col: 13, offset: 1117},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 43, col: 15, offset: 1119},
							label: "val",
							expr: &zeroOrOneExpr{
								pos: position{line: 43, col: 19, offset: 1123},
								expr: &ruleRefExpr{
									pos:  position{line: 43, col: 19, offset: 1123},
									name: "Value",
								},
							},
						},
						&ruleRefExpr{
							pos:  position{line: 43, col: 26, offset: 1130},
							name: "_",
						},
						&ruleRefExpr{
							pos:  position{line: 43, col: 28, offset: 1132},
							name: "EOF",
						},
					},
				},
			},
		},
		{
			name: "Object",
			pos:  position{line: 53, col: 1, offset: 1300},
			expr: &actionExpr{
				pos: position{line: 53, col: 11, offset: 1310},
				run: (*parser).callonObject1,
				expr: &seqExpr{
					pos: position{line: 53, col: 11, offset: 1310},
					exprs: []interface{}{
						&ruleRefExpr{
							pos:  position{line: 53, col: 11, offset: 1310},
							name: "LBrace",
						},
						&ruleRefExpr{
							pos:  position{line: 53, col: 18, offset: 1317},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 53, col: 20, offset: 1319},
							label: "vals",
							expr: &zeroOrMoreExpr{
								pos: position{line: 53, col: 25, offset: 1324},
								expr: &ruleRefExpr{
									pos:  position{line: 53, col: 25, offset: 1324},
									name: "KVPair",
								},
							},
						},
						&ruleRefExpr{
							pos:  position{line: 53, col: 33, offset: 1332},
							name: "_",
						},
						&ruleRefExpr{
							pos:  position{line: 53, col: 35, offset: 1334},
							name: "RBrace",
						},
					},
				},
			},
		},
		{
			name: "KVPair",
			pos:  position{line: 60, col: 1, offset: 1474},
			expr: &actionExpr{
				pos: position{line: 60, col: 11, offset: 1484},
				run: (*parser).callonKVPair1,
				expr: &seqExpr{
					pos: position{line: 60, col: 11, offset: 1484},
					exprs: []interface{}{
						&ruleRefExpr{
							pos:  position{line: 60, col: 11, offset: 1484},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 60, col: 13, offset: 1486},
							label: "k",
							expr: &ruleRefExpr{
								pos:  position{line: 60, col: 15, offset: 1488},
								name: "InlineKey",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 60, col: 25, offset: 1498},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 60, col: 27, offset: 1500},
							label: "v",
							expr: &ruleRefExpr{
								pos:  position{line: 60, col: 29, offset: 1502},
								name: "Value",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 60, col: 35, offset: 1508},
							name: "_",
						},
					},
				},
			},
		},
		{
			name: "InlineObject",
			pos:  position{line: 66, col: 1, offset: 1650},
			expr: &actionExpr{
				pos: position{line: 66, col: 17, offset: 1666},
				run: (*parser).callonInlineObject1,
				expr: &labeledExpr{
					pos:   position{line: 66, col: 17, offset: 1666},
					label: "vals",
					expr: &oneOrMoreExpr{
						pos: position{line: 66, col: 22, offset: 1671},
						expr: &ruleRefExpr{
							pos:  position{line: 66, col: 22, offset: 1671},
							name: "InlineKVPair",
						},
					},
				},
			},
		},
		{
			name: "InlineKVPair",
			pos:  position{line: 72, col: 1, offset: 1784},
			expr: &actionExpr{
				pos: position{line: 72, col: 17, offset: 1800},
				run: (*parser).callonInlineKVPair1,
				expr: &seqExpr{
					pos: position{line: 72, col: 17, offset: 1800},
					exprs: []interface{}{
						&zeroOrMoreExpr{
							pos: position{line: 72, col: 17, offset: 1800},
							expr: &ruleRefExpr{
								pos:  position{line: 72, col: 17, offset: 1800},
								name: "Space",
							},
						},
						&labeledExpr{
							pos:   position{line: 72, col: 24, offset: 1807},
							label: "k",
							expr: &ruleRefExpr{
								pos:  position{line: 72, col: 26, offset: 1809},
								name: "InlineKey",
							},
						},
						&labeledExpr{
							pos:   position{line: 72, col: 36, offset: 1819},
							label: "v",
							expr: &ruleRefExpr{
								pos:  position{line: 72, col: 38, offset: 1821},
								name: "Value",
							},
						},
					},
				},
			},
		},
		{
			name: "List",
			pos:  position{line: 82, col: 1, offset: 1982},
			expr: &actionExpr{
				pos: position{line: 82, col: 9, offset: 1990},
				run: (*parser).callonList1,
				expr: &seqExpr{
					pos: position{line: 82, col: 9, offset: 1990},
					exprs: []interface{}{
						&ruleRefExpr{
							pos:  position{line: 82, col: 9, offset: 1990},
							name: "LSBracket",
						},
						&ruleRefExpr{
							pos:  position{line: 82, col: 19, offset: 2000},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 82, col: 21, offset: 2002},
							label: "vals",
							expr: &zeroOrMoreExpr{
								pos: position{line: 82, col: 26, offset: 2007},
								expr: &ruleRefExpr{
									pos:  position{line: 82, col: 26, offset: 2007},
									name: "ListItem",
								},
							},
						},
						&ruleRefExpr{
							pos:  position{line: 82, col: 36, offset: 2017},
							name: "_",
						},
						&ruleRefExpr{
							pos:  position{line: 82, col: 38, offset: 2019},
							name: "RSBracket",
						},
					},
				},
			},
		},
		{
			name: "ListItem",
			pos:  position{line: 91, col: 1, offset: 2171},
			expr: &actionExpr{
				pos: position{line: 91, col: 13, offset: 2183},
				run: (*parser).callonListItem1,
				expr: &seqExpr{
					pos: position{line: 91, col: 13, offset: 2183},
					exprs: []interface{}{
						&ruleRefExpr{
							pos:  position{line: 91, col: 13, offset: 2183},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 91, col: 15, offset: 2185},
							label: "val",
							expr: &ruleRefExpr{
								pos:  position{line: 91, col: 19, offset: 2189},
								name: "Value",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 91, col: 25, offset: 2195},
							name: "_",
						},
					},
				},
			},
		},
		{
			name: "Value",
			pos:  position{line: 102, col: 1, offset: 2372},
			expr: &choiceExpr{
				pos: position{line: 102, col: 10, offset: 2381},
				alternatives: []interface{}{
					&ruleRefExpr{
						pos:  position{line: 102, col: 10, offset: 2381},
						name: "InlineValue",
					},
					&ruleRefExpr{
						pos:  position{line: 102, col: 24, offset: 2395},
						name: "String",
					},
					&ruleRefExpr{
						pos:  position{line: 102, col: 33, offset: 2404},
						name: "List",
					},
					&ruleRefExpr{
						pos:  position{line: 102, col: 40, offset: 2411},
						name: "Object",
					},
				},
			},
		},
		{
			name: "InlineValue",
			pos:  position{line: 110, col: 1, offset: 2560},
			expr: &choiceExpr{
				pos: position{line: 110, col: 16, offset: 2575},
				alternatives: []interface{}{
					&ruleRefExpr{
						pos:  position{line: 110, col: 16, offset: 2575},
						name: "EnvVar",
					},
					&ruleRefExpr{
						pos:  position{line: 110, col: 25, offset: 2584},
						name: "InlineObject",
					},
					&ruleRefExpr{
						pos:  position{line: 110, col: 40, offset: 2599},
						name: "InlineString",
					},
					&ruleRefExpr{
						pos:  position{line: 110, col: 55, offset: 2614},
						name: "Integer",
					},
					&ruleRefExpr{
						pos:  position{line: 110, col: 65, offset: 2624},
						name: "Boolean",
					},
				},
			},
		},
		{
			name: "InlineKey",
			pos:  position{line: 117, col: 1, offset: 2816},
			expr: &actionExpr{
				pos: position{line: 117, col: 14, offset: 2829},
				run: (*parser).callonInlineKey1,
				expr: &seqExpr{
					pos: position{line: 117, col: 14, offset: 2829},
					exprs: []interface{}{
						&labeledExpr{
							pos:   position{line: 117, col: 14, offset: 2829},
							label: "val",
							expr: &choiceExpr{
								pos: position{line: 117, col: 19, offset: 2834},
								alternatives: []interface{}{
									&ruleRefExpr{
										pos:  position{line: 117, col: 19, offset: 2834},
										name: "InlineString",
									},
									&ruleRefExpr{
										pos:  position{line: 117, col: 34, offset: 2849},
										name: "QuotlessString",
									},
								},
							},
						},
						&ruleRefExpr{
							pos:  position{line: 117, col: 50, offset: 2865},
							name: "Colon",
						},
						&zeroOrMoreExpr{
							pos: position{line: 117, col: 56, offset: 2871},
							expr: &ruleRefExpr{
								pos:  position{line: 117, col: 56, offset: 2871},
								name: "Space",
							},
						},
					},
				},
			},
		},
		{
			name: "EnvVar",
			pos:  position{line: 125, col: 1, offset: 3077},
			expr: &actionExpr{
				pos: position{line: 125, col: 11, offset: 3087},
				run: (*parser).callonEnvVar1,
				expr: &seqExpr{
					pos: position{line: 125, col: 11, offset: 3087},
					exprs: []interface{}{
						&ruleRefExpr{
							pos:  position{line: 125, col: 11, offset: 3087},
							name: "Dollar",
						},
						&ruleRefExpr{
							pos:  position{line: 125, col: 18, offset: 3094},
							name: "LBrace",
						},
						&ruleRefExpr{
							pos:  position{line: 125, col: 25, offset: 3101},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 125, col: 27, offset: 3103},
							label: "val",
							expr: &ruleRefExpr{
								pos:  position{line: 125, col: 31, offset: 3107},
								name: "QuotlessString",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 125, col: 46, offset: 3122},
							name: "_",
						},
						&ruleRefExpr{
							pos:  position{line: 125, col: 48, offset: 3124},
							name: "RBrace",
						},
					},
				},
			},
		},
		{
			name: "QuotlessString",
			pos:  position{line: 134, col: 1, offset: 3411},
			expr: &actionExpr{
				pos: position{line: 134, col: 19, offset: 3429},
				run: (*parser).callonQuotlessString1,
				expr: &oneOrMoreExpr{
					pos: position{line: 134, col: 19, offset: 3429},
					expr: &seqExpr{
						pos: position{line: 134, col: 20, offset: 3430},
						exprs: []interface{}{
							&notExpr{
								pos: position{line: 134, col: 20, offset: 3430},
								expr: &ruleRefExpr{
									pos:  position{line: 134, col: 21, offset: 3431},
									name: "Reserved",
								},
							},
							&notExpr{
								pos: position{line: 134, col: 30, offset: 3440},
								expr: &ruleRefExpr{
									pos:  position{line: 134, col: 31, offset: 3441},
									name: "Space",
								},
							},
							&notExpr{
								pos: position{line: 134, col: 37, offset: 3447},
								expr: &ruleRefExpr{
									pos:  position{line: 134, col: 38, offset: 3448},
									name: "LBreak",
								},
							},
							&ruleRefExpr{
								pos:  position{line: 134, col: 46, offset: 3456},
								name: "Any",
							},
						},
					},
				},
			},
		},
		{
			name: "String",
			pos:  position{line: 145, col: 1, offset: 3671},
			expr: &actionExpr{
				pos: position{line: 145, col: 11, offset: 3681},
				run: (*parser).callonString1,
				expr: &seqExpr{
					pos: position{line: 145, col: 11, offset: 3681},
					exprs: []interface{}{
						&ruleRefExpr{
							pos:  position{line: 145, col: 11, offset: 3681},
							name: "GAccent",
						},
						&zeroOrMoreExpr{
							pos: position{line: 145, col: 19, offset: 3689},
							expr: &seqExpr{
								pos: position{line: 145, col: 20, offset: 3690},
								exprs: []interface{}{
									&notExpr{
										pos: position{line: 145, col: 20, offset: 3690},
										expr: &ruleRefExpr{
											pos:  position{line: 145, col: 21, offset: 3691},
											name: "GAccent",
										},
									},
									&ruleRefExpr{
										pos:  position{line: 145, col: 29, offset: 3699},
										name: "Any",
									},
								},
							},
						},
						&ruleRefExpr{
							pos:  position{line: 145, col: 35, offset: 3705},
							name: "GAccent",
						},
					},
				},
			},
		},
		{
			name: "InlineString",
			pos:  position{line: 154, col: 1, offset: 3954},
			expr: &actionExpr{
				pos: position{line: 154, col: 17, offset: 3970},
				run: (*parser).callonInlineString1,
				expr: &seqExpr{
					pos: position{line: 154, col: 17, offset: 3970},
					exprs: []interface{}{
						&ruleRefExpr{
							pos:  position{line: 154, col: 17, offset: 3970},
							name: "DQuote",
						},
						&zeroOrMoreExpr{
							pos: position{line: 154, col: 24, offset: 3977},
							expr: &seqExpr{
								pos: position{line: 154, col: 25, offset: 3978},
								exprs: []interface{}{
									&notExpr{
										pos: position{line: 154, col: 25, offset: 3978},
										expr: &ruleRefExpr{
											pos:  position{line: 154, col: 26, offset: 3979},
											name: "DQuote",
										},
									},
									&notExpr{
										pos: position{line: 154, col: 33, offset: 3986},
										expr: &ruleRefExpr{
											pos:  position{line: 154, col: 34, offset: 3987},
											name: "LBreak",
										},
									},
									&ruleRefExpr{
										pos:  position{line: 154, col: 41, offset: 3994},
										name: "Any",
									},
								},
							},
						},
						&ruleRefExpr{
							pos:  position{line: 154, col: 47, offset: 4000},
							name: "DQuote",
						},
					},
				},
			},
		},
		{
			name: "Integer",
			pos:  position{line: 163, col: 1, offset: 4170},
			expr: &actionExpr{
				pos: position{line: 163, col: 12, offset: 4181},
				run: (*parser).callonInteger1,
				expr: &seqExpr{
					pos: position{line: 163, col: 12, offset: 4181},
					exprs: []interface{}{
						&zeroOrOneExpr{
							pos: position{line: 163, col: 12, offset: 4181},
							expr: &litMatcher{
								pos:        position{line: 163, col: 12, offset: 4181},
								val:        "-",
								ignoreCase: false,
							},
						},
						&choiceExpr{
							pos: position{line: 163, col: 18, offset: 4187},
							alternatives: []interface{}{
								&litMatcher{
									pos:        position{line: 163, col: 18, offset: 4187},
									val:        "0",
									ignoreCase: false,
								},
								&seqExpr{
									pos: position{line: 163, col: 24, offset: 4193},
									exprs: []interface{}{
										&oneOrMoreExpr{
											pos: position{line: 163, col: 24, offset: 4193},
											expr: &charClassMatcher{
												pos:        position{line: 163, col: 24, offset: 4193},
												val:        "[1-9]",
												ranges:     []rune{'1', '9'},
												ignoreCase: false,
												inverted:   false,
											},
										},
										&zeroOrMoreExpr{
											pos: position{line: 163, col: 31, offset: 4200},
											expr: &charClassMatcher{
												pos:        position{line: 163, col: 31, offset: 4200},
												val:        "[0-9]",
												ranges:     []rune{'0', '9'},
												ignoreCase: false,
												inverted:   false,
											},
										},
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "Boolean",
			pos:  position{line: 170, col: 1, offset: 4314},
			expr: &actionExpr{
				pos: position{line: 170, col: 12, offset: 4325},
				run: (*parser).callonBoolean1,
				expr: &choiceExpr{
					pos: position{line: 170, col: 13, offset: 4326},
					alternatives: []interface{}{
						&litMatcher{
							pos:        position{line: 170, col: 13, offset: 4326},
							val:        "true",
							ignoreCase: false,
						},
						&litMatcher{
							pos:        position{line: 170, col: 22, offset: 4335},
							val:        "false",
							ignoreCase: false,
						},
					},
				},
			},
		},
		{
			name: "Comment",
			pos:  position{line: 180, col: 1, offset: 4555},
			expr: &seqExpr{
				pos: position{line: 180, col: 12, offset: 4566},
				exprs: []interface{}{
					&ruleRefExpr{
						pos:  position{line: 180, col: 12, offset: 4566},
						name: "Sharp",
					},
					&zeroOrMoreExpr{
						pos: position{line: 180, col: 18, offset: 4572},
						expr: &seqExpr{
							pos: position{line: 180, col: 19, offset: 4573},
							exprs: []interface{}{
								&notExpr{
									pos: position{line: 180, col: 19, offset: 4573},
									expr: &ruleRefExpr{
										pos:  position{line: 180, col: 20, offset: 4574},
										name: "LBreak",
									},
								},
								&ruleRefExpr{
									pos:  position{line: 180, col: 27, offset: 4581},
									name: "Any",
								},
							},
						},
					},
					&ruleRefExpr{
						pos:  position{line: 180, col: 33, offset: 4587},
						name: "LBreak",
					},
				},
			},
		},
		{
			name:        "_",
			displayName: "\"whitespace\"",
			pos:         position{line: 183, col: 1, offset: 4660},
			expr: &zeroOrMoreExpr{
				pos: position{line: 183, col: 19, offset: 4678},
				expr: &choiceExpr{
					pos: position{line: 183, col: 20, offset: 4679},
					alternatives: []interface{}{
						&ruleRefExpr{
							pos:  position{line: 183, col: 20, offset: 4679},
							name: "Space",
						},
						&ruleRefExpr{
							pos:  position{line: 183, col: 28, offset: 4687},
							name: "LBreak",
						},
						&ruleRefExpr{
							pos:  position{line: 183, col: 37, offset: 4696},
							name: "Comment",
						},
					},
				},
			},
		},
		{
			name: "Reserved",
			pos:  position{line: 191, col: 1, offset: 4838},
			expr: &choiceExpr{
				pos: position{line: 191, col: 13, offset: 4850},
				alternatives: []interface{}{
					&ruleRefExpr{
						pos:  position{line: 191, col: 13, offset: 4850},
						name: "Colon",
					},
					&ruleRefExpr{
						pos:  position{line: 191, col: 21, offset: 4858},
						name: "Dollar",
					},
					&ruleRefExpr{
						pos:  position{line: 191, col: 30, offset: 4867},
						name: "Sharp",
					},
					&ruleRefExpr{
						pos:  position{line: 191, col: 38, offset: 4875},
						name: "GAccent",
					},
					&ruleRefExpr{
						pos:  position{line: 191, col: 48, offset: 4885},
						name: "DQuote",
					},
					&ruleRefExpr{
						pos:  position{line: 191, col: 57, offset: 4894},
						name: "LSBracket",
					},
					&ruleRefExpr{
						pos:  position{line: 191, col: 69, offset: 4906},
						name: "RSBracket",
					},
					&ruleRefExpr{
						pos:  position{line: 192, col: 4, offset: 4919},
						name: "LBrace",
					},
					&ruleRefExpr{
						pos:  position{line: 192, col: 13, offset: 4928},
						name: "RBrace",
					},
					&ruleRefExpr{
						pos:  position{line: 192, col: 22, offset: 4937},
						name: "LParenthesis",
					},
					&ruleRefExpr{
						pos:  position{line: 192, col: 37, offset: 4952},
						name: "RParenthesis",
					},
					&ruleRefExpr{
						pos:  position{line: 192, col: 52, offset: 4967},
						name: "Percent",
					},
					&ruleRefExpr{
						pos:  position{line: 192, col: 62, offset: 4977},
						name: "At",
					},
				},
			},
		},
		{
			name: "Colon",
			pos:  position{line: 194, col: 1, offset: 4981},
			expr: &litMatcher{
				pos:        position{line: 194, col: 10, offset: 4990},
				val:        ":",
				ignoreCase: false,
			},
		},
		{
			name: "Dollar",
			pos:  position{line: 195, col: 1, offset: 5011},
			expr: &litMatcher{
				pos:        position{line: 195, col: 11, offset: 5021},
				val:        "$",
				ignoreCase: false,
			},
		},
		{
			name: "Sharp",
			pos:  position{line: 196, col: 1, offset: 5042},
			expr: &litMatcher{
				pos:        position{line: 196, col: 10, offset: 5051},
				val:        "#",
				ignoreCase: false,
			},
		},
		{
			name: "GAccent",
			pos:  position{line: 198, col: 1, offset: 5073},
			expr: &litMatcher{
				pos:        position{line: 198, col: 12, offset: 5084},
				val:        "`",
				ignoreCase: false,
			},
		},
		{
			name: "DQuote",
			pos:  position{line: 199, col: 1, offset: 5111},
			expr: &litMatcher{
				pos:        position{line: 199, col: 11, offset: 5121},
				val:        "\"",
				ignoreCase: false,
			},
		},
		{
			name: "LSBracket",
			pos:  position{line: 202, col: 1, offset: 5210},
			expr: &litMatcher{
				pos:        position{line: 202, col: 14, offset: 5223},
				val:        "[",
				ignoreCase: false,
			},
		},
		{
			name: "RSBracket",
			pos:  position{line: 203, col: 1, offset: 5257},
			expr: &litMatcher{
				pos:        position{line: 203, col: 14, offset: 5270},
				val:        "]",
				ignoreCase: false,
			},
		},
		{
			name: "LBrace",
			pos:  position{line: 206, col: 1, offset: 5378},
			expr: &litMatcher{
				pos:        position{line: 206, col: 11, offset: 5388},
				val:        "{",
				ignoreCase: false,
			},
		},
		{
			name: "RBrace",
			pos:  position{line: 207, col: 1, offset: 5413},
			expr: &litMatcher{
				pos:        position{line: 207, col: 11, offset: 5423},
				val:        "}",
				ignoreCase: false,
			},
		},
		{
			name: "LParenthesis",
			pos:  position{line: 210, col: 1, offset: 5495},
			expr: &litMatcher{
				pos:        position{line: 210, col: 17, offset: 5511},
				val:        "(",
				ignoreCase: false,
			},
		},
		{
			name: "RParenthesis",
			pos:  position{line: 211, col: 1, offset: 5544},
			expr: &litMatcher{
				pos:        position{line: 211, col: 17, offset: 5560},
				val:        ")",
				ignoreCase: false,
			},
		},
		{
			name: "Percent",
			pos:  position{line: 212, col: 1, offset: 5594},
			expr: &litMatcher{
				pos:        position{line: 212, col: 12, offset: 5605},
				val:        "%",
				ignoreCase: false,
			},
		},
		{
			name: "At",
			pos:  position{line: 213, col: 1, offset: 5632},
			expr: &litMatcher{
				pos:        position{line: 213, col: 7, offset: 5638},
				val:        "@",
				ignoreCase: false,
			},
		},
		{
			name: "LBreak",
			pos:  position{line: 217, col: 1, offset: 5798},
			expr: &choiceExpr{
				pos: position{line: 217, col: 11, offset: 5808},
				alternatives: []interface{}{
					&litMatcher{
						pos:        position{line: 217, col: 11, offset: 5808},
						val:        "\r\n",
						ignoreCase: false,
					},
					&litMatcher{
						pos:        position{line: 217, col: 20, offset: 5817},
						val:        "\r",
						ignoreCase: false,
					},
					&litMatcher{
						pos:        position{line: 217, col: 27, offset: 5824},
						val:        "\n",
						ignoreCase: false,
					},
				},
			},
		},
		{
			name: "Space",
			pos:  position{line: 220, col: 1, offset: 5861},
			expr: &choiceExpr{
				pos: position{line: 220, col: 10, offset: 5870},
				alternatives: []interface{}{
					&litMatcher{
						pos:        position{line: 220, col: 10, offset: 5870},
						val:        " ",
						ignoreCase: false,
					},
					&litMatcher{
						pos:        position{line: 220, col: 16, offset: 5876},
						val:        "\t",
						ignoreCase: false,
					},
				},
			},
		},
		{
			name: "Any",
			pos:  position{line: 223, col: 1, offset: 5907},
			expr: &anyMatcher{
				line: 223, col: 8, offset: 5914,
			},
		},
		{
			name: "EOF",
			pos:  position{line: 226, col: 1, offset: 5969},
			expr: &notExpr{
				pos: position{line: 226, col: 8, offset: 5976},
				expr: &anyMatcher{
					line: 226, col: 9, offset: 5977,
				},
			},
		},
	},
}

func (c *current) onEspresso1(val interface{}) (interface{}, error) {
	return val, nil
}

func (p *parser) callonEspresso1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onEspresso1(stack["val"])
}

func (c *current) onObject1(vals interface{}) (interface{}, error) {
	return sliceOfKVSlicesToObject(vals)
}

func (p *parser) callonObject1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onObject1(stack["vals"])
}

func (c *current) onKVPair1(k, v interface{}) (interface{}, error) {
	return []interface{}{k, v}, nil
}

func (p *parser) callonKVPair1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onKVPair1(stack["k"], stack["v"])
}

func (c *current) onInlineObject1(vals interface{}) (interface{}, error) {
	return sliceOfKVSlicesToObject(vals)
}

func (p *parser) callonInlineObject1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onInlineObject1(stack["vals"])
}

func (c *current) onInlineKVPair1(k, v interface{}) (interface{}, error) {
	return []interface{}{k, v}, nil
}

func (p *parser) callonInlineKVPair1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onInlineKVPair1(stack["k"], stack["v"])
}

func (c *current) onList1(vals interface{}) (interface{}, error) {
	return vals, nil
}

func (p *parser) callonList1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onList1(stack["vals"])
}

func (c *current) onListItem1(val interface{}) (interface{}, error) {
	return val, nil
}

func (p *parser) callonListItem1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onListItem1(stack["val"])
}

func (c *current) onInlineKey1(val interface{}) (interface{}, error) {
	return val.(string), nil
}

func (p *parser) callonInlineKey1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onInlineKey1(stack["val"])
}

func (c *current) onEnvVar1(val interface{}) (interface{}, error) {
	return os.Getenv(val.(string)), nil
}

func (p *parser) callonEnvVar1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onEnvVar1(stack["val"])
}

func (c *current) onQuotlessString1() (interface{}, error) {
	return string(c.text), nil
}

func (p *parser) callonQuotlessString1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onQuotlessString1()
}

func (c *current) onString1() (interface{}, error) {
	return strconv.Unquote(string(c.text))
}

func (p *parser) callonString1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onString1()
}

func (c *current) onInlineString1() (interface{}, error) {
	return strconv.Unquote(string(c.text))
}

func (p *parser) callonInlineString1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onInlineString1()
}

func (c *current) onInteger1() (interface{}, error) {
	return strconv.ParseInt(string(c.text), 10, 64)
}

func (p *parser) callonInteger1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onInteger1()
}

func (c *current) onBoolean1() (interface{}, error) {
	if string(c.text) == "true" {
		return true, nil
	}
	return false, nil
}

func (p *parser) callonBoolean1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onBoolean1()
}

var (
	// errNoRule is returned when the grammar to parse has no rule.
	errNoRule = errors.New("grammar has no rule")

	// errInvalidEncoding is returned when the source is not properly
	// utf8-encoded.
	errInvalidEncoding = errors.New("invalid encoding")

	// errNoMatch is returned if no match could be found.
	errNoMatch = errors.New("no match found")
)

// Option is a function that can set an option on the parser. It returns
// the previous setting as an Option.
type Option func(*parser) Option

// Debug creates an Option to set the debug flag to b. When set to true,
// debugging information is printed to stdout while parsing.
//
// The default is false.
func Debug(b bool) Option {
	return func(p *parser) Option {
		old := p.debug
		p.debug = b
		return Debug(old)
	}
}

// Memoize creates an Option to set the memoize flag to b. When set to true,
// the parser will cache all results so each expression is evaluated only
// once. This guarantees linear parsing time even for pathological cases,
// at the expense of more memory and slower times for typical cases.
//
// The default is false.
func Memoize(b bool) Option {
	return func(p *parser) Option {
		old := p.memoize
		p.memoize = b
		return Memoize(old)
	}
}

// Recover creates an Option to set the recover flag to b. When set to
// true, this causes the parser to recover from panics and convert it
// to an error. Setting it to false can be useful while debugging to
// access the full stack trace.
//
// The default is true.
func Recover(b bool) Option {
	return func(p *parser) Option {
		old := p.recover
		p.recover = b
		return Recover(old)
	}
}

// ParseFile parses the file identified by filename.
func ParseFile(filename string, opts ...Option) (interface{}, error) {
	f, err := os.Open(filename)
	if err != nil {
		return nil, err
	}
	defer f.Close()
	return ParseReader(filename, f, opts...)
}

// ParseReader parses the data from r using filename as information in the
// error messages.
func ParseReader(filename string, r io.Reader, opts ...Option) (interface{}, error) {
	b, err := ioutil.ReadAll(r)
	if err != nil {
		return nil, err
	}

	return Parse(filename, b, opts...)
}

// Parse parses the data from b using filename as information in the
// error messages.
func Parse(filename string, b []byte, opts ...Option) (interface{}, error) {
	return newParser(filename, b, opts...).parse(g)
}

// position records a position in the text.
type position struct {
	line, col, offset int
}

func (p position) String() string {
	return fmt.Sprintf("%d:%d [%d]", p.line, p.col, p.offset)
}

// savepoint stores all state required to go back to this point in the
// parser.
type savepoint struct {
	position
	rn rune
	w  int
}

type current struct {
	pos  position // start position of the match
	text []byte   // raw text of the match
}

// the AST types...

type grammar struct {
	pos   position
	rules []*rule
}

type rule struct {
	pos         position
	name        string
	displayName string
	expr        interface{}
}

type choiceExpr struct {
	pos          position
	alternatives []interface{}
}

type actionExpr struct {
	pos  position
	expr interface{}
	run  func(*parser) (interface{}, error)
}

type seqExpr struct {
	pos   position
	exprs []interface{}
}

type labeledExpr struct {
	pos   position
	label string
	expr  interface{}
}

type expr struct {
	pos  position
	expr interface{}
}

type andExpr expr
type notExpr expr
type zeroOrOneExpr expr
type zeroOrMoreExpr expr
type oneOrMoreExpr expr

type ruleRefExpr struct {
	pos  position
	name string
}

type andCodeExpr struct {
	pos position
	run func(*parser) (bool, error)
}

type notCodeExpr struct {
	pos position
	run func(*parser) (bool, error)
}

type litMatcher struct {
	pos        position
	val        string
	ignoreCase bool
}

type charClassMatcher struct {
	pos        position
	val        string
	chars      []rune
	ranges     []rune
	classes    []*unicode.RangeTable
	ignoreCase bool
	inverted   bool
}

type anyMatcher position

// errList cumulates the errors found by the parser.
type errList []error

func (e *errList) add(err error) {
	*e = append(*e, err)
}

func (e errList) err() error {
	if len(e) == 0 {
		return nil
	}
	e.dedupe()
	return e
}

func (e *errList) dedupe() {
	var cleaned []error
	set := make(map[string]bool)
	for _, err := range *e {
		if msg := err.Error(); !set[msg] {
			set[msg] = true
			cleaned = append(cleaned, err)
		}
	}
	*e = cleaned
}

func (e errList) Error() string {
	switch len(e) {
	case 0:
		return ""
	case 1:
		return e[0].Error()
	default:
		var buf bytes.Buffer

		for i, err := range e {
			if i > 0 {
				buf.WriteRune('\n')
			}
			buf.WriteString(err.Error())
		}
		return buf.String()
	}
}

// parserError wraps an error with a prefix indicating the rule in which
// the error occurred. The original error is stored in the Inner field.
type parserError struct {
	Inner  error
	pos    position
	prefix string
}

// Error returns the error message.
func (p *parserError) Error() string {
	return p.prefix + ": " + p.Inner.Error()
}

// newParser creates a parser with the specified input source and options.
func newParser(filename string, b []byte, opts ...Option) *parser {
	p := &parser{
		filename: filename,
		errs:     new(errList),
		data:     b,
		pt:       savepoint{position: position{line: 1}},
		recover:  true,
	}
	p.setOptions(opts)
	return p
}

// setOptions applies the options to the parser.
func (p *parser) setOptions(opts []Option) {
	for _, opt := range opts {
		opt(p)
	}
}

type resultTuple struct {
	v   interface{}
	b   bool
	end savepoint
}

type parser struct {
	filename string
	pt       savepoint
	cur      current

	data []byte
	errs *errList

	recover bool
	debug   bool
	depth   int

	memoize bool
	// memoization table for the packrat algorithm:
	// map[offset in source] map[expression or rule] {value, match}
	memo map[int]map[interface{}]resultTuple

	// rules table, maps the rule identifier to the rule node
	rules map[string]*rule
	// variables stack, map of label to value
	vstack []map[string]interface{}
	// rule stack, allows identification of the current rule in errors
	rstack []*rule

	// stats
	exprCnt int
}

// push a variable set on the vstack.
func (p *parser) pushV() {
	if cap(p.vstack) == len(p.vstack) {
		// create new empty slot in the stack
		p.vstack = append(p.vstack, nil)
	} else {
		// slice to 1 more
		p.vstack = p.vstack[:len(p.vstack)+1]
	}

	// get the last args set
	m := p.vstack[len(p.vstack)-1]
	if m != nil && len(m) == 0 {
		// empty map, all good
		return
	}

	m = make(map[string]interface{})
	p.vstack[len(p.vstack)-1] = m
}

// pop a variable set from the vstack.
func (p *parser) popV() {
	// if the map is not empty, clear it
	m := p.vstack[len(p.vstack)-1]
	if len(m) > 0 {
		// GC that map
		p.vstack[len(p.vstack)-1] = nil
	}
	p.vstack = p.vstack[:len(p.vstack)-1]
}

func (p *parser) print(prefix, s string) string {
	if !p.debug {
		return s
	}

	fmt.Printf("%s %d:%d:%d: %s [%#U]\n",
		prefix, p.pt.line, p.pt.col, p.pt.offset, s, p.pt.rn)
	return s
}

func (p *parser) in(s string) string {
	p.depth++
	return p.print(strings.Repeat(" ", p.depth)+">", s)
}

func (p *parser) out(s string) string {
	p.depth--
	return p.print(strings.Repeat(" ", p.depth)+"<", s)
}

func (p *parser) addErr(err error) {
	p.addErrAt(err, p.pt.position)
}

func (p *parser) addErrAt(err error, pos position) {
	var buf bytes.Buffer
	if p.filename != "" {
		buf.WriteString(p.filename)
	}
	if buf.Len() > 0 {
		buf.WriteString(":")
	}
	buf.WriteString(fmt.Sprintf("%d:%d (%d)", pos.line, pos.col, pos.offset))
	if len(p.rstack) > 0 {
		if buf.Len() > 0 {
			buf.WriteString(": ")
		}
		rule := p.rstack[len(p.rstack)-1]
		if rule.displayName != "" {
			buf.WriteString("rule " + rule.displayName)
		} else {
			buf.WriteString("rule " + rule.name)
		}
	}
	pe := &parserError{Inner: err, prefix: buf.String()}
	p.errs.add(pe)
}

// read advances the parser to the next rune.
func (p *parser) read() {
	p.pt.offset += p.pt.w
	rn, n := utf8.DecodeRune(p.data[p.pt.offset:])
	p.pt.rn = rn
	p.pt.w = n
	p.pt.col++
	if rn == '\n' {
		p.pt.line++
		p.pt.col = 0
	}

	if rn == utf8.RuneError {
		if n > 0 {
			p.addErr(errInvalidEncoding)
		}
	}
}

// restore parser position to the savepoint pt.
func (p *parser) restore(pt savepoint) {
	if p.debug {
		defer p.out(p.in("restore"))
	}
	if pt.offset == p.pt.offset {
		return
	}
	p.pt = pt
}

// get the slice of bytes from the savepoint start to the current position.
func (p *parser) sliceFrom(start savepoint) []byte {
	return p.data[start.position.offset:p.pt.position.offset]
}

func (p *parser) getMemoized(node interface{}) (resultTuple, bool) {
	if len(p.memo) == 0 {
		return resultTuple{}, false
	}
	m := p.memo[p.pt.offset]
	if len(m) == 0 {
		return resultTuple{}, false
	}
	res, ok := m[node]
	return res, ok
}

func (p *parser) setMemoized(pt savepoint, node interface{}, tuple resultTuple) {
	if p.memo == nil {
		p.memo = make(map[int]map[interface{}]resultTuple)
	}
	m := p.memo[pt.offset]
	if m == nil {
		m = make(map[interface{}]resultTuple)
		p.memo[pt.offset] = m
	}
	m[node] = tuple
}

func (p *parser) buildRulesTable(g *grammar) {
	p.rules = make(map[string]*rule, len(g.rules))
	for _, r := range g.rules {
		p.rules[r.name] = r
	}
}

func (p *parser) parse(g *grammar) (val interface{}, err error) {
	if len(g.rules) == 0 {
		p.addErr(errNoRule)
		return nil, p.errs.err()
	}

	// TODO : not super critical but this could be generated
	p.buildRulesTable(g)

	if p.recover {
		// panic can be used in action code to stop parsing immediately
		// and return the panic as an error.
		defer func() {
			if e := recover(); e != nil {
				if p.debug {
					defer p.out(p.in("panic handler"))
				}
				val = nil
				switch e := e.(type) {
				case error:
					p.addErr(e)
				default:
					p.addErr(fmt.Errorf("%v", e))
				}
				err = p.errs.err()
			}
		}()
	}

	// start rule is rule [0]
	p.read() // advance to first rune
	val, ok := p.parseRule(g.rules[0])
	if !ok {
		if len(*p.errs) == 0 {
			// make sure this doesn't go out silently
			p.addErr(errNoMatch)
		}
		return nil, p.errs.err()
	}
	return val, p.errs.err()
}

func (p *parser) parseRule(rule *rule) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseRule " + rule.name))
	}

	if p.memoize {
		res, ok := p.getMemoized(rule)
		if ok {
			p.restore(res.end)
			return res.v, res.b
		}
	}

	start := p.pt
	p.rstack = append(p.rstack, rule)
	p.pushV()
	val, ok := p.parseExpr(rule.expr)
	p.popV()
	p.rstack = p.rstack[:len(p.rstack)-1]
	if ok && p.debug {
		p.print(strings.Repeat(" ", p.depth)+"MATCH", string(p.sliceFrom(start)))
	}

	if p.memoize {
		p.setMemoized(start, rule, resultTuple{val, ok, p.pt})
	}
	return val, ok
}

func (p *parser) parseExpr(expr interface{}) (interface{}, bool) {
	var pt savepoint
	var ok bool

	if p.memoize {
		res, ok := p.getMemoized(expr)
		if ok {
			p.restore(res.end)
			return res.v, res.b
		}
		pt = p.pt
	}

	p.exprCnt++
	var val interface{}
	switch expr := expr.(type) {
	case *actionExpr:
		val, ok = p.parseActionExpr(expr)
	case *andCodeExpr:
		val, ok = p.parseAndCodeExpr(expr)
	case *andExpr:
		val, ok = p.parseAndExpr(expr)
	case *anyMatcher:
		val, ok = p.parseAnyMatcher(expr)
	case *charClassMatcher:
		val, ok = p.parseCharClassMatcher(expr)
	case *choiceExpr:
		val, ok = p.parseChoiceExpr(expr)
	case *labeledExpr:
		val, ok = p.parseLabeledExpr(expr)
	case *litMatcher:
		val, ok = p.parseLitMatcher(expr)
	case *notCodeExpr:
		val, ok = p.parseNotCodeExpr(expr)
	case *notExpr:
		val, ok = p.parseNotExpr(expr)
	case *oneOrMoreExpr:
		val, ok = p.parseOneOrMoreExpr(expr)
	case *ruleRefExpr:
		val, ok = p.parseRuleRefExpr(expr)
	case *seqExpr:
		val, ok = p.parseSeqExpr(expr)
	case *zeroOrMoreExpr:
		val, ok = p.parseZeroOrMoreExpr(expr)
	case *zeroOrOneExpr:
		val, ok = p.parseZeroOrOneExpr(expr)
	default:
		panic(fmt.Sprintf("unknown expression type %T", expr))
	}
	if p.memoize {
		p.setMemoized(pt, expr, resultTuple{val, ok, p.pt})
	}
	return val, ok
}

func (p *parser) parseActionExpr(act *actionExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseActionExpr"))
	}

	start := p.pt
	val, ok := p.parseExpr(act.expr)
	if ok {
		p.cur.pos = start.position
		p.cur.text = p.sliceFrom(start)
		actVal, err := act.run(p)
		if err != nil {
			p.addErrAt(err, start.position)
		}
		val = actVal
	}
	if ok && p.debug {
		p.print(strings.Repeat(" ", p.depth)+"MATCH", string(p.sliceFrom(start)))
	}
	return val, ok
}

func (p *parser) parseAndCodeExpr(and *andCodeExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseAndCodeExpr"))
	}

	ok, err := and.run(p)
	if err != nil {
		p.addErr(err)
	}
	return nil, ok
}

func (p *parser) parseAndExpr(and *andExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseAndExpr"))
	}

	pt := p.pt
	p.pushV()
	_, ok := p.parseExpr(and.expr)
	p.popV()
	p.restore(pt)
	return nil, ok
}

func (p *parser) parseAnyMatcher(any *anyMatcher) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseAnyMatcher"))
	}

	if p.pt.rn != utf8.RuneError {
		start := p.pt
		p.read()
		return p.sliceFrom(start), true
	}
	return nil, false
}

func (p *parser) parseCharClassMatcher(chr *charClassMatcher) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseCharClassMatcher"))
	}

	cur := p.pt.rn
	// can't match EOF
	if cur == utf8.RuneError {
		return nil, false
	}
	start := p.pt
	if chr.ignoreCase {
		cur = unicode.ToLower(cur)
	}

	// try to match in the list of available chars
	for _, rn := range chr.chars {
		if rn == cur {
			if chr.inverted {
				return nil, false
			}
			p.read()
			return p.sliceFrom(start), true
		}
	}

	// try to match in the list of ranges
	for i := 0; i < len(chr.ranges); i += 2 {
		if cur >= chr.ranges[i] && cur <= chr.ranges[i+1] {
			if chr.inverted {
				return nil, false
			}
			p.read()
			return p.sliceFrom(start), true
		}
	}

	// try to match in the list of Unicode classes
	for _, cl := range chr.classes {
		if unicode.Is(cl, cur) {
			if chr.inverted {
				return nil, false
			}
			p.read()
			return p.sliceFrom(start), true
		}
	}

	if chr.inverted {
		p.read()
		return p.sliceFrom(start), true
	}
	return nil, false
}

func (p *parser) parseChoiceExpr(ch *choiceExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseChoiceExpr"))
	}

	for _, alt := range ch.alternatives {
		p.pushV()
		val, ok := p.parseExpr(alt)
		p.popV()
		if ok {
			return val, ok
		}
	}
	return nil, false
}

func (p *parser) parseLabeledExpr(lab *labeledExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseLabeledExpr"))
	}

	p.pushV()
	val, ok := p.parseExpr(lab.expr)
	p.popV()
	if ok && lab.label != "" {
		m := p.vstack[len(p.vstack)-1]
		m[lab.label] = val
	}
	return val, ok
}

func (p *parser) parseLitMatcher(lit *litMatcher) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseLitMatcher"))
	}

	start := p.pt
	for _, want := range lit.val {
		cur := p.pt.rn
		if lit.ignoreCase {
			cur = unicode.ToLower(cur)
		}
		if cur != want {
			p.restore(start)
			return nil, false
		}
		p.read()
	}
	return p.sliceFrom(start), true
}

func (p *parser) parseNotCodeExpr(not *notCodeExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseNotCodeExpr"))
	}

	ok, err := not.run(p)
	if err != nil {
		p.addErr(err)
	}
	return nil, !ok
}

func (p *parser) parseNotExpr(not *notExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseNotExpr"))
	}

	pt := p.pt
	p.pushV()
	_, ok := p.parseExpr(not.expr)
	p.popV()
	p.restore(pt)
	return nil, !ok
}

func (p *parser) parseOneOrMoreExpr(expr *oneOrMoreExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseOneOrMoreExpr"))
	}

	var vals []interface{}

	for {
		p.pushV()
		val, ok := p.parseExpr(expr.expr)
		p.popV()
		if !ok {
			if len(vals) == 0 {
				// did not match once, no match
				return nil, false
			}
			return vals, true
		}
		vals = append(vals, val)
	}
}

func (p *parser) parseRuleRefExpr(ref *ruleRefExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseRuleRefExpr " + ref.name))
	}

	if ref.name == "" {
		panic(fmt.Sprintf("%s: invalid rule: missing name", ref.pos))
	}

	rule := p.rules[ref.name]
	if rule == nil {
		p.addErr(fmt.Errorf("undefined rule: %s", ref.name))
		return nil, false
	}
	return p.parseRule(rule)
}

func (p *parser) parseSeqExpr(seq *seqExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseSeqExpr"))
	}

	var vals []interface{}

	pt := p.pt
	for _, expr := range seq.exprs {
		val, ok := p.parseExpr(expr)
		if !ok {
			p.restore(pt)
			return nil, false
		}
		vals = append(vals, val)
	}
	return vals, true
}

func (p *parser) parseZeroOrMoreExpr(expr *zeroOrMoreExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseZeroOrMoreExpr"))
	}

	var vals []interface{}

	for {
		p.pushV()
		val, ok := p.parseExpr(expr.expr)
		p.popV()
		if !ok {
			return vals, true
		}
		vals = append(vals, val)
	}
}

func (p *parser) parseZeroOrOneExpr(expr *zeroOrOneExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseZeroOrOneExpr"))
	}

	p.pushV()
	val, _ := p.parseExpr(expr.expr)
	p.popV()
	// whether it matched or not, consider it a match
	return val, true
}

func rangeTable(class string) *unicode.RangeTable {
	if rt, ok := unicode.Categories[class]; ok {
		return rt
	}
	if rt, ok := unicode.Properties[class]; ok {
		return rt
	}
	if rt, ok := unicode.Scripts[class]; ok {
		return rt
	}

	// cannot happen
	panic(fmt.Sprintf("invalid Unicode class: %s", class))
}
