// Package parser is used for parsing Espresso, a human friendly
// format based on a subset of CoffeeScript, as defined by spec [1].
//
// It is automatically generated by pigeon [2].
// Do not edit manually, make changes to PEG file instead.
//
// [1]: https://github.com/anonx/espresso
// [2]: https://github.com/PuerkitoBio/pigeon
package parser

import (
	"bytes"
	"errors"
	"fmt"
	"io"
	"io/ioutil"
	"os"
	"strconv"
	"strings"
	"unicode"
	"unicode/utf8"
)

func interfaceSlice(v interface{}) []interface{} {
	if v == nil {
		return nil
	}
	return v.([]interface{})
}

var g = &grammar{
	rules: []*rule{
		{
			name: "Espresso",
			pos:  position{line: 32, col: 1, offset: 577},
			expr: &actionExpr{
				pos: position{line: 32, col: 13, offset: 589},
				run: (*parser).callonEspresso1,
				expr: &seqExpr{
					pos: position{line: 32, col: 13, offset: 589},
					exprs: []interface{}{
						&ruleRefExpr{
							pos:  position{line: 32, col: 13, offset: 589},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 32, col: 15, offset: 591},
							label: "val",
							expr: &zeroOrOneExpr{
								pos: position{line: 32, col: 19, offset: 595},
								expr: &ruleRefExpr{
									pos:  position{line: 32, col: 19, offset: 595},
									name: "Value",
								},
							},
						},
						&ruleRefExpr{
							pos:  position{line: 32, col: 26, offset: 602},
							name: "_",
						},
						&ruleRefExpr{
							pos:  position{line: 32, col: 28, offset: 604},
							name: "EOF",
						},
					},
				},
			},
		},
		{
			name: "Object",
			pos:  position{line: 36, col: 1, offset: 630},
			expr: &actionExpr{
				pos: position{line: 36, col: 11, offset: 640},
				run: (*parser).callonObject1,
				expr: &seqExpr{
					pos: position{line: 36, col: 11, offset: 640},
					exprs: []interface{}{
						&litMatcher{
							pos:        position{line: 36, col: 11, offset: 640},
							val:        "{",
							ignoreCase: false,
						},
						&ruleRefExpr{
							pos:  position{line: 36, col: 15, offset: 644},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 36, col: 17, offset: 646},
							label: "vals",
							expr: &zeroOrMoreExpr{
								pos: position{line: 36, col: 22, offset: 651},
								expr: &actionExpr{
									pos: position{line: 36, col: 23, offset: 652},
									run: (*parser).callonObject7,
									expr: &seqExpr{
										pos: position{line: 36, col: 23, offset: 652},
										exprs: []interface{}{
											&ruleRefExpr{
												pos:  position{line: 36, col: 23, offset: 652},
												name: "_",
											},
											&labeledExpr{
												pos:   position{line: 36, col: 25, offset: 654},
												label: "val",
												expr: &ruleRefExpr{
													pos:  position{line: 36, col: 29, offset: 658},
													name: "KVPair",
												},
											},
											&ruleRefExpr{
												pos:  position{line: 36, col: 36, offset: 665},
												name: "_",
											},
										},
									},
								},
							},
						},
						&ruleRefExpr{
							pos:  position{line: 36, col: 58, offset: 687},
							name: "_",
						},
						&litMatcher{
							pos:        position{line: 36, col: 60, offset: 689},
							val:        "}",
							ignoreCase: false,
						},
					},
				},
			},
		},
		{
			name: "KVPair",
			pos:  position{line: 46, col: 1, offset: 881},
			expr: &actionExpr{
				pos: position{line: 46, col: 11, offset: 891},
				run: (*parser).callonKVPair1,
				expr: &seqExpr{
					pos: position{line: 46, col: 11, offset: 891},
					exprs: []interface{}{
						&labeledExpr{
							pos:   position{line: 46, col: 11, offset: 891},
							label: "k",
							expr: &ruleRefExpr{
								pos:  position{line: 46, col: 13, offset: 893},
								name: "InlineKey",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 46, col: 23, offset: 903},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 46, col: 25, offset: 905},
							label: "v",
							expr: &ruleRefExpr{
								pos:  position{line: 46, col: 27, offset: 907},
								name: "Value",
							},
						},
					},
				},
			},
		},
		{
			name: "InlineObject",
			pos:  position{line: 50, col: 1, offset: 951},
			expr: &actionExpr{
				pos: position{line: 50, col: 17, offset: 967},
				run: (*parser).callonInlineObject1,
				expr: &labeledExpr{
					pos:   position{line: 50, col: 17, offset: 967},
					label: "vals",
					expr: &oneOrMoreExpr{
						pos: position{line: 50, col: 22, offset: 972},
						expr: &actionExpr{
							pos: position{line: 50, col: 23, offset: 973},
							run: (*parser).callonInlineObject4,
							expr: &seqExpr{
								pos: position{line: 50, col: 23, offset: 973},
								exprs: []interface{}{
									&zeroOrMoreExpr{
										pos: position{line: 50, col: 23, offset: 973},
										expr: &ruleRefExpr{
											pos:  position{line: 50, col: 23, offset: 973},
											name: "Space",
										},
									},
									&labeledExpr{
										pos:   position{line: 50, col: 30, offset: 980},
										label: "val",
										expr: &ruleRefExpr{
											pos:  position{line: 50, col: 34, offset: 984},
											name: "InlineKVPair",
										},
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "InlineKVPair",
			pos:  position{line: 60, col: 1, offset: 1205},
			expr: &actionExpr{
				pos: position{line: 60, col: 17, offset: 1221},
				run: (*parser).callonInlineKVPair1,
				expr: &seqExpr{
					pos: position{line: 60, col: 17, offset: 1221},
					exprs: []interface{}{
						&labeledExpr{
							pos:   position{line: 60, col: 17, offset: 1221},
							label: "k",
							expr: &ruleRefExpr{
								pos:  position{line: 60, col: 19, offset: 1223},
								name: "InlineKey",
							},
						},
						&labeledExpr{
							pos:   position{line: 60, col: 29, offset: 1233},
							label: "v",
							expr: &ruleRefExpr{
								pos:  position{line: 60, col: 31, offset: 1235},
								name: "Value",
							},
						},
					},
				},
			},
		},
		{
			name: "List",
			pos:  position{line: 64, col: 1, offset: 1279},
			expr: &actionExpr{
				pos: position{line: 64, col: 9, offset: 1287},
				run: (*parser).callonList1,
				expr: &seqExpr{
					pos: position{line: 64, col: 9, offset: 1287},
					exprs: []interface{}{
						&litMatcher{
							pos:        position{line: 64, col: 9, offset: 1287},
							val:        "[",
							ignoreCase: false,
						},
						&labeledExpr{
							pos:   position{line: 64, col: 13, offset: 1291},
							label: "vals",
							expr: &zeroOrMoreExpr{
								pos: position{line: 64, col: 18, offset: 1296},
								expr: &ruleRefExpr{
									pos:  position{line: 64, col: 18, offset: 1296},
									name: "ListBody",
								},
							},
						},
						&litMatcher{
							pos:        position{line: 64, col: 28, offset: 1306},
							val:        "]",
							ignoreCase: false,
						},
					},
				},
			},
		},
		{
			name: "ListBody",
			pos:  position{line: 68, col: 1, offset: 1333},
			expr: &actionExpr{
				pos: position{line: 68, col: 13, offset: 1345},
				run: (*parser).callonListBody1,
				expr: &seqExpr{
					pos: position{line: 68, col: 13, offset: 1345},
					exprs: []interface{}{
						&ruleRefExpr{
							pos:  position{line: 68, col: 13, offset: 1345},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 68, col: 15, offset: 1347},
							label: "val",
							expr: &ruleRefExpr{
								pos:  position{line: 68, col: 19, offset: 1351},
								name: "Value",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 68, col: 25, offset: 1357},
							name: "_",
						},
					},
				},
			},
		},
		{
			name: "Value",
			pos:  position{line: 72, col: 1, offset: 1381},
			expr: &choiceExpr{
				pos: position{line: 72, col: 10, offset: 1390},
				alternatives: []interface{}{
					&ruleRefExpr{
						pos:  position{line: 72, col: 10, offset: 1390},
						name: "InlineObject",
					},
					&ruleRefExpr{
						pos:  position{line: 72, col: 25, offset: 1405},
						name: "String",
					},
					&ruleRefExpr{
						pos:  position{line: 72, col: 34, offset: 1414},
						name: "Object",
					},
					&ruleRefExpr{
						pos:  position{line: 72, col: 43, offset: 1423},
						name: "List",
					},
					&ruleRefExpr{
						pos:  position{line: 72, col: 50, offset: 1430},
						name: "InlineValue",
					},
				},
			},
		},
		{
			name: "InlineValue",
			pos:  position{line: 74, col: 1, offset: 1443},
			expr: &choiceExpr{
				pos: position{line: 74, col: 16, offset: 1458},
				alternatives: []interface{}{
					&ruleRefExpr{
						pos:  position{line: 74, col: 16, offset: 1458},
						name: "Boolean",
					},
					&ruleRefExpr{
						pos:  position{line: 74, col: 26, offset: 1468},
						name: "InlineString",
					},
					&ruleRefExpr{
						pos:  position{line: 74, col: 41, offset: 1483},
						name: "Integer",
					},
				},
			},
		},
		{
			name: "InlineKey",
			pos:  position{line: 76, col: 1, offset: 1492},
			expr: &actionExpr{
				pos: position{line: 76, col: 14, offset: 1505},
				run: (*parser).callonInlineKey1,
				expr: &seqExpr{
					pos: position{line: 76, col: 14, offset: 1505},
					exprs: []interface{}{
						&labeledExpr{
							pos:   position{line: 76, col: 14, offset: 1505},
							label: "val",
							expr: &choiceExpr{
								pos: position{line: 76, col: 19, offset: 1510},
								alternatives: []interface{}{
									&ruleRefExpr{
										pos:  position{line: 76, col: 19, offset: 1510},
										name: "InlineValue",
									},
									&ruleRefExpr{
										pos:  position{line: 76, col: 33, offset: 1524},
										name: "PureKey",
									},
								},
							},
						},
						&ruleRefExpr{
							pos:  position{line: 76, col: 42, offset: 1533},
							name: "KeyDelim",
						},
						&zeroOrMoreExpr{
							pos: position{line: 76, col: 51, offset: 1542},
							expr: &ruleRefExpr{
								pos:  position{line: 76, col: 51, offset: 1542},
								name: "Space",
							},
						},
					},
				},
			},
		},
		{
			name: "PureKey",
			pos:  position{line: 80, col: 1, offset: 1590},
			expr: &actionExpr{
				pos: position{line: 80, col: 12, offset: 1601},
				run: (*parser).callonPureKey1,
				expr: &oneOrMoreExpr{
					pos: position{line: 80, col: 12, offset: 1601},
					expr: &seqExpr{
						pos: position{line: 80, col: 13, offset: 1602},
						exprs: []interface{}{
							&notExpr{
								pos: position{line: 80, col: 13, offset: 1602},
								expr: &ruleRefExpr{
									pos:  position{line: 80, col: 14, offset: 1603},
									name: "KeyDelim",
								},
							},
							&notExpr{
								pos: position{line: 80, col: 23, offset: 1612},
								expr: &ruleRefExpr{
									pos:  position{line: 80, col: 24, offset: 1613},
									name: "Space",
								},
							},
							&notExpr{
								pos: position{line: 80, col: 30, offset: 1619},
								expr: &ruleRefExpr{
									pos:  position{line: 80, col: 31, offset: 1620},
									name: "Quote",
								},
							},
							&notExpr{
								pos: position{line: 80, col: 37, offset: 1626},
								expr: &ruleRefExpr{
									pos:  position{line: 80, col: 38, offset: 1627},
									name: "InlineQuote",
								},
							},
							&notExpr{
								pos: position{line: 80, col: 50, offset: 1639},
								expr: &ruleRefExpr{
									pos:  position{line: 80, col: 51, offset: 1640},
									name: "LBreak",
								},
							},
							&notExpr{
								pos: position{line: 80, col: 58, offset: 1647},
								expr: &litMatcher{
									pos:        position{line: 80, col: 59, offset: 1648},
									val:        "[",
									ignoreCase: false,
								},
							},
							&notExpr{
								pos: position{line: 80, col: 63, offset: 1652},
								expr: &litMatcher{
									pos:        position{line: 80, col: 64, offset: 1653},
									val:        "]",
									ignoreCase: false,
								},
							},
							&notExpr{
								pos: position{line: 80, col: 68, offset: 1657},
								expr: &litMatcher{
									pos:        position{line: 80, col: 69, offset: 1658},
									val:        "{",
									ignoreCase: false,
								},
							},
							&notExpr{
								pos: position{line: 80, col: 73, offset: 1662},
								expr: &litMatcher{
									pos:        position{line: 80, col: 74, offset: 1663},
									val:        "}",
									ignoreCase: false,
								},
							},
							&ruleRefExpr{
								pos:  position{line: 80, col: 79, offset: 1668},
								name: "Any",
							},
						},
					},
				},
			},
		},
		{
			name: "String",
			pos:  position{line: 84, col: 1, offset: 1707},
			expr: &actionExpr{
				pos: position{line: 84, col: 11, offset: 1717},
				run: (*parser).callonString1,
				expr: &seqExpr{
					pos: position{line: 84, col: 11, offset: 1717},
					exprs: []interface{}{
						&ruleRefExpr{
							pos:  position{line: 84, col: 11, offset: 1717},
							name: "Quote",
						},
						&zeroOrMoreExpr{
							pos: position{line: 84, col: 17, offset: 1723},
							expr: &seqExpr{
								pos: position{line: 84, col: 18, offset: 1724},
								exprs: []interface{}{
									&notExpr{
										pos: position{line: 84, col: 18, offset: 1724},
										expr: &ruleRefExpr{
											pos:  position{line: 84, col: 19, offset: 1725},
											name: "Quote",
										},
									},
									&ruleRefExpr{
										pos:  position{line: 84, col: 25, offset: 1731},
										name: "Any",
									},
								},
							},
						},
						&ruleRefExpr{
							pos:  position{line: 84, col: 31, offset: 1737},
							name: "Quote",
						},
					},
				},
			},
		},
		{
			name: "InlineString",
			pos:  position{line: 88, col: 1, offset: 1788},
			expr: &actionExpr{
				pos: position{line: 88, col: 17, offset: 1804},
				run: (*parser).callonInlineString1,
				expr: &seqExpr{
					pos: position{line: 88, col: 17, offset: 1804},
					exprs: []interface{}{
						&ruleRefExpr{
							pos:  position{line: 88, col: 17, offset: 1804},
							name: "InlineQuote",
						},
						&zeroOrMoreExpr{
							pos: position{line: 88, col: 29, offset: 1816},
							expr: &seqExpr{
								pos: position{line: 88, col: 30, offset: 1817},
								exprs: []interface{}{
									&notExpr{
										pos: position{line: 88, col: 30, offset: 1817},
										expr: &ruleRefExpr{
											pos:  position{line: 88, col: 31, offset: 1818},
											name: "InlineQuote",
										},
									},
									&notExpr{
										pos: position{line: 88, col: 43, offset: 1830},
										expr: &ruleRefExpr{
											pos:  position{line: 88, col: 44, offset: 1831},
											name: "LBreak",
										},
									},
									&ruleRefExpr{
										pos:  position{line: 88, col: 51, offset: 1838},
										name: "Any",
									},
								},
							},
						},
						&ruleRefExpr{
							pos:  position{line: 88, col: 57, offset: 1844},
							name: "InlineQuote",
						},
					},
				},
			},
		},
		{
			name: "Integer",
			pos:  position{line: 92, col: 1, offset: 1901},
			expr: &actionExpr{
				pos: position{line: 92, col: 12, offset: 1912},
				run: (*parser).callonInteger1,
				expr: &seqExpr{
					pos: position{line: 92, col: 12, offset: 1912},
					exprs: []interface{}{
						&zeroOrOneExpr{
							pos: position{line: 92, col: 12, offset: 1912},
							expr: &litMatcher{
								pos:        position{line: 92, col: 12, offset: 1912},
								val:        "-",
								ignoreCase: false,
							},
						},
						&choiceExpr{
							pos: position{line: 92, col: 18, offset: 1918},
							alternatives: []interface{}{
								&litMatcher{
									pos:        position{line: 92, col: 18, offset: 1918},
									val:        "0",
									ignoreCase: false,
								},
								&seqExpr{
									pos: position{line: 92, col: 24, offset: 1924},
									exprs: []interface{}{
										&oneOrMoreExpr{
											pos: position{line: 92, col: 24, offset: 1924},
											expr: &charClassMatcher{
												pos:        position{line: 92, col: 24, offset: 1924},
												val:        "[1-9]",
												ranges:     []rune{'1', '9'},
												ignoreCase: false,
												inverted:   false,
											},
										},
										&zeroOrMoreExpr{
											pos: position{line: 92, col: 31, offset: 1931},
											expr: &charClassMatcher{
												pos:        position{line: 92, col: 31, offset: 1931},
												val:        "[0-9]",
												ranges:     []rune{'0', '9'},
												ignoreCase: false,
												inverted:   false,
											},
										},
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "Boolean",
			pos:  position{line: 96, col: 1, offset: 1992},
			expr: &actionExpr{
				pos: position{line: 96, col: 12, offset: 2003},
				run: (*parser).callonBoolean1,
				expr: &choiceExpr{
					pos: position{line: 96, col: 13, offset: 2004},
					alternatives: []interface{}{
						&litMatcher{
							pos:        position{line: 96, col: 13, offset: 2004},
							val:        "true",
							ignoreCase: false,
						},
						&litMatcher{
							pos:        position{line: 96, col: 22, offset: 2013},
							val:        "false",
							ignoreCase: false,
						},
					},
				},
			},
		},
		{
			name: "Comment",
			pos:  position{line: 103, col: 1, offset: 2099},
			expr: &seqExpr{
				pos: position{line: 103, col: 12, offset: 2110},
				exprs: []interface{}{
					&litMatcher{
						pos:        position{line: 103, col: 12, offset: 2110},
						val:        "#",
						ignoreCase: false,
					},
					&zeroOrMoreExpr{
						pos: position{line: 103, col: 16, offset: 2114},
						expr: &seqExpr{
							pos: position{line: 103, col: 17, offset: 2115},
							exprs: []interface{}{
								&notExpr{
									pos: position{line: 103, col: 17, offset: 2115},
									expr: &ruleRefExpr{
										pos:  position{line: 103, col: 18, offset: 2116},
										name: "LBreak",
									},
								},
								&ruleRefExpr{
									pos:  position{line: 103, col: 25, offset: 2123},
									name: "Any",
								},
							},
						},
					},
					&ruleRefExpr{
						pos:  position{line: 103, col: 31, offset: 2129},
						name: "LBreak",
					},
				},
			},
		},
		{
			name: "Any",
			pos:  position{line: 105, col: 1, offset: 2137},
			expr: &anyMatcher{
				line: 105, col: 8, offset: 2144,
			},
		},
		{
			name:        "_",
			displayName: "\"whitespace\"",
			pos:         position{line: 107, col: 1, offset: 2147},
			expr: &zeroOrMoreExpr{
				pos: position{line: 107, col: 19, offset: 2165},
				expr: &choiceExpr{
					pos: position{line: 107, col: 20, offset: 2166},
					alternatives: []interface{}{
						&ruleRefExpr{
							pos:  position{line: 107, col: 20, offset: 2166},
							name: "Space",
						},
						&ruleRefExpr{
							pos:  position{line: 107, col: 28, offset: 2174},
							name: "LBreak",
						},
						&ruleRefExpr{
							pos:  position{line: 107, col: 37, offset: 2183},
							name: "Comment",
						},
					},
				},
			},
		},
		{
			name: "LBreak",
			pos:  position{line: 109, col: 1, offset: 2194},
			expr: &choiceExpr{
				pos: position{line: 109, col: 11, offset: 2204},
				alternatives: []interface{}{
					&litMatcher{
						pos:        position{line: 109, col: 11, offset: 2204},
						val:        "\r\n",
						ignoreCase: false,
					},
					&litMatcher{
						pos:        position{line: 109, col: 20, offset: 2213},
						val:        "\r",
						ignoreCase: false,
					},
					&litMatcher{
						pos:        position{line: 109, col: 27, offset: 2220},
						val:        "\n",
						ignoreCase: false,
					},
				},
			},
		},
		{
			name: "Space",
			pos:  position{line: 111, col: 1, offset: 2226},
			expr: &choiceExpr{
				pos: position{line: 111, col: 10, offset: 2235},
				alternatives: []interface{}{
					&litMatcher{
						pos:        position{line: 111, col: 10, offset: 2235},
						val:        " ",
						ignoreCase: false,
					},
					&litMatcher{
						pos:        position{line: 111, col: 16, offset: 2241},
						val:        "\t",
						ignoreCase: false,
					},
				},
			},
		},
		{
			name: "KeyDelim",
			pos:  position{line: 113, col: 1, offset: 2247},
			expr: &seqExpr{
				pos: position{line: 113, col: 13, offset: 2259},
				exprs: []interface{}{
					&litMatcher{
						pos:        position{line: 113, col: 13, offset: 2259},
						val:        ":",
						ignoreCase: false,
					},
					&zeroOrMoreExpr{
						pos: position{line: 113, col: 17, offset: 2263},
						expr: &ruleRefExpr{
							pos:  position{line: 113, col: 17, offset: 2263},
							name: "Space",
						},
					},
				},
			},
		},
		{
			name: "Quote",
			pos:  position{line: 115, col: 1, offset: 2271},
			expr: &litMatcher{
				pos:        position{line: 115, col: 10, offset: 2280},
				val:        "`",
				ignoreCase: false,
			},
		},
		{
			name: "InlineQuote",
			pos:  position{line: 117, col: 1, offset: 2285},
			expr: &litMatcher{
				pos:        position{line: 117, col: 16, offset: 2300},
				val:        "\"",
				ignoreCase: false,
			},
		},
		{
			name: "EOF",
			pos:  position{line: 119, col: 1, offset: 2305},
			expr: &notExpr{
				pos: position{line: 119, col: 8, offset: 2312},
				expr: &anyMatcher{
					line: 119, col: 9, offset: 2313,
				},
			},
		},
	},
}

func (c *current) onEspresso1(val interface{}) (interface{}, error) {
	return val, nil
}

func (p *parser) callonEspresso1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onEspresso1(stack["val"])
}

func (c *current) onObject7(val interface{}) (interface{}, error) {
	return val, nil
}

func (p *parser) callonObject7() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onObject7(stack["val"])
}

func (c *current) onObject1(vals interface{}) (interface{}, error) {
	lst := interfaceSlice(vals)
	obj := make(map[interface{}]interface{}, len(lst))
	for i := 0; i < len(lst); i++ {
		t := interfaceSlice(lst[i])
		obj[t[0]] = t[1]
	}
	return obj, nil
}

func (p *parser) callonObject1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onObject1(stack["vals"])
}

func (c *current) onKVPair1(k, v interface{}) (interface{}, error) {
	return []interface{}{k, v}, nil
}

func (p *parser) callonKVPair1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onKVPair1(stack["k"], stack["v"])
}

func (c *current) onInlineObject4(val interface{}) (interface{}, error) {
	return val, nil
}

func (p *parser) callonInlineObject4() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onInlineObject4(stack["val"])
}

func (c *current) onInlineObject1(vals interface{}) (interface{}, error) {
	lst := interfaceSlice(vals)
	obj := make(map[interface{}]interface{}, len(lst))
	for i := 0; i < len(lst); i++ {
		t := interfaceSlice(lst[i])
		obj[t[0]] = t[1]
	}
	return obj, nil
}

func (p *parser) callonInlineObject1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onInlineObject1(stack["vals"])
}

func (c *current) onInlineKVPair1(k, v interface{}) (interface{}, error) {
	return []interface{}{k, v}, nil
}

func (p *parser) callonInlineKVPair1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onInlineKVPair1(stack["k"], stack["v"])
}

func (c *current) onList1(vals interface{}) (interface{}, error) {
	return vals, nil
}

func (p *parser) callonList1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onList1(stack["vals"])
}

func (c *current) onListBody1(val interface{}) (interface{}, error) {
	return val, nil
}

func (p *parser) callonListBody1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onListBody1(stack["val"])
}

func (c *current) onInlineKey1(val interface{}) (interface{}, error) {
	return fmt.Sprintf("%v", val), nil
}

func (p *parser) callonInlineKey1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onInlineKey1(stack["val"])
}

func (c *current) onPureKey1() (interface{}, error) {
	return string(c.text), nil
}

func (p *parser) callonPureKey1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onPureKey1()
}

func (c *current) onString1() (interface{}, error) {
	return strconv.Unquote(string(c.text))
}

func (p *parser) callonString1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onString1()
}

func (c *current) onInlineString1() (interface{}, error) {
	return strconv.Unquote(string(c.text))
}

func (p *parser) callonInlineString1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onInlineString1()
}

func (c *current) onInteger1() (interface{}, error) {
	return strconv.ParseInt(string(c.text), 10, 0)
}

func (p *parser) callonInteger1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onInteger1()
}

func (c *current) onBoolean1() (interface{}, error) {
	if string(c.text) == "true" {
		return true, nil
	}
	return false, nil
}

func (p *parser) callonBoolean1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onBoolean1()
}

var (
	// errNoRule is returned when the grammar to parse has no rule.
	errNoRule = errors.New("grammar has no rule")

	// errInvalidEncoding is returned when the source is not properly
	// utf8-encoded.
	errInvalidEncoding = errors.New("invalid encoding")

	// errNoMatch is returned if no match could be found.
	errNoMatch = errors.New("no match found")
)

// Option is a function that can set an option on the parser. It returns
// the previous setting as an Option.
type Option func(*parser) Option

// Debug creates an Option to set the debug flag to b. When set to true,
// debugging information is printed to stdout while parsing.
//
// The default is false.
func Debug(b bool) Option {
	return func(p *parser) Option {
		old := p.debug
		p.debug = b
		return Debug(old)
	}
}

// Memoize creates an Option to set the memoize flag to b. When set to true,
// the parser will cache all results so each expression is evaluated only
// once. This guarantees linear parsing time even for pathological cases,
// at the expense of more memory and slower times for typical cases.
//
// The default is false.
func Memoize(b bool) Option {
	return func(p *parser) Option {
		old := p.memoize
		p.memoize = b
		return Memoize(old)
	}
}

// Recover creates an Option to set the recover flag to b. When set to
// true, this causes the parser to recover from panics and convert it
// to an error. Setting it to false can be useful while debugging to
// access the full stack trace.
//
// The default is true.
func Recover(b bool) Option {
	return func(p *parser) Option {
		old := p.recover
		p.recover = b
		return Recover(old)
	}
}

// ParseFile parses the file identified by filename.
func ParseFile(filename string, opts ...Option) (interface{}, error) {
	f, err := os.Open(filename)
	if err != nil {
		return nil, err
	}
	defer f.Close()
	return ParseReader(filename, f, opts...)
}

// ParseReader parses the data from r using filename as information in the
// error messages.
func ParseReader(filename string, r io.Reader, opts ...Option) (interface{}, error) {
	b, err := ioutil.ReadAll(r)
	if err != nil {
		return nil, err
	}

	return Parse(filename, b, opts...)
}

// Parse parses the data from b using filename as information in the
// error messages.
func Parse(filename string, b []byte, opts ...Option) (interface{}, error) {
	return newParser(filename, b, opts...).parse(g)
}

// position records a position in the text.
type position struct {
	line, col, offset int
}

func (p position) String() string {
	return fmt.Sprintf("%d:%d [%d]", p.line, p.col, p.offset)
}

// savepoint stores all state required to go back to this point in the
// parser.
type savepoint struct {
	position
	rn rune
	w  int
}

type current struct {
	pos  position // start position of the match
	text []byte   // raw text of the match
}

// the AST types...

type grammar struct {
	pos   position
	rules []*rule
}

type rule struct {
	pos         position
	name        string
	displayName string
	expr        interface{}
}

type choiceExpr struct {
	pos          position
	alternatives []interface{}
}

type actionExpr struct {
	pos  position
	expr interface{}
	run  func(*parser) (interface{}, error)
}

type seqExpr struct {
	pos   position
	exprs []interface{}
}

type labeledExpr struct {
	pos   position
	label string
	expr  interface{}
}

type expr struct {
	pos  position
	expr interface{}
}

type andExpr expr
type notExpr expr
type zeroOrOneExpr expr
type zeroOrMoreExpr expr
type oneOrMoreExpr expr

type ruleRefExpr struct {
	pos  position
	name string
}

type andCodeExpr struct {
	pos position
	run func(*parser) (bool, error)
}

type notCodeExpr struct {
	pos position
	run func(*parser) (bool, error)
}

type litMatcher struct {
	pos        position
	val        string
	ignoreCase bool
}

type charClassMatcher struct {
	pos        position
	val        string
	chars      []rune
	ranges     []rune
	classes    []*unicode.RangeTable
	ignoreCase bool
	inverted   bool
}

type anyMatcher position

// errList cumulates the errors found by the parser.
type errList []error

func (e *errList) add(err error) {
	*e = append(*e, err)
}

func (e errList) err() error {
	if len(e) == 0 {
		return nil
	}
	e.dedupe()
	return e
}

func (e *errList) dedupe() {
	var cleaned []error
	set := make(map[string]bool)
	for _, err := range *e {
		if msg := err.Error(); !set[msg] {
			set[msg] = true
			cleaned = append(cleaned, err)
		}
	}
	*e = cleaned
}

func (e errList) Error() string {
	switch len(e) {
	case 0:
		return ""
	case 1:
		return e[0].Error()
	default:
		var buf bytes.Buffer

		for i, err := range e {
			if i > 0 {
				buf.WriteRune('\n')
			}
			buf.WriteString(err.Error())
		}
		return buf.String()
	}
}

// parserError wraps an error with a prefix indicating the rule in which
// the error occurred. The original error is stored in the Inner field.
type parserError struct {
	Inner  error
	pos    position
	prefix string
}

// Error returns the error message.
func (p *parserError) Error() string {
	return p.prefix + ": " + p.Inner.Error()
}

// newParser creates a parser with the specified input source and options.
func newParser(filename string, b []byte, opts ...Option) *parser {
	p := &parser{
		filename: filename,
		errs:     new(errList),
		data:     b,
		pt:       savepoint{position: position{line: 1}},
		recover:  true,
	}
	p.setOptions(opts)
	return p
}

// setOptions applies the options to the parser.
func (p *parser) setOptions(opts []Option) {
	for _, opt := range opts {
		opt(p)
	}
}

type resultTuple struct {
	v   interface{}
	b   bool
	end savepoint
}

type parser struct {
	filename string
	pt       savepoint
	cur      current

	data []byte
	errs *errList

	recover bool
	debug   bool
	depth   int

	memoize bool
	// memoization table for the packrat algorithm:
	// map[offset in source] map[expression or rule] {value, match}
	memo map[int]map[interface{}]resultTuple

	// rules table, maps the rule identifier to the rule node
	rules map[string]*rule
	// variables stack, map of label to value
	vstack []map[string]interface{}
	// rule stack, allows identification of the current rule in errors
	rstack []*rule

	// stats
	exprCnt int
}

// push a variable set on the vstack.
func (p *parser) pushV() {
	if cap(p.vstack) == len(p.vstack) {
		// create new empty slot in the stack
		p.vstack = append(p.vstack, nil)
	} else {
		// slice to 1 more
		p.vstack = p.vstack[:len(p.vstack)+1]
	}

	// get the last args set
	m := p.vstack[len(p.vstack)-1]
	if m != nil && len(m) == 0 {
		// empty map, all good
		return
	}

	m = make(map[string]interface{})
	p.vstack[len(p.vstack)-1] = m
}

// pop a variable set from the vstack.
func (p *parser) popV() {
	// if the map is not empty, clear it
	m := p.vstack[len(p.vstack)-1]
	if len(m) > 0 {
		// GC that map
		p.vstack[len(p.vstack)-1] = nil
	}
	p.vstack = p.vstack[:len(p.vstack)-1]
}

func (p *parser) print(prefix, s string) string {
	if !p.debug {
		return s
	}

	fmt.Printf("%s %d:%d:%d: %s [%#U]\n",
		prefix, p.pt.line, p.pt.col, p.pt.offset, s, p.pt.rn)
	return s
}

func (p *parser) in(s string) string {
	p.depth++
	return p.print(strings.Repeat(" ", p.depth)+">", s)
}

func (p *parser) out(s string) string {
	p.depth--
	return p.print(strings.Repeat(" ", p.depth)+"<", s)
}

func (p *parser) addErr(err error) {
	p.addErrAt(err, p.pt.position)
}

func (p *parser) addErrAt(err error, pos position) {
	var buf bytes.Buffer
	if p.filename != "" {
		buf.WriteString(p.filename)
	}
	if buf.Len() > 0 {
		buf.WriteString(":")
	}
	buf.WriteString(fmt.Sprintf("%d:%d (%d)", pos.line, pos.col, pos.offset))
	if len(p.rstack) > 0 {
		if buf.Len() > 0 {
			buf.WriteString(": ")
		}
		rule := p.rstack[len(p.rstack)-1]
		if rule.displayName != "" {
			buf.WriteString("rule " + rule.displayName)
		} else {
			buf.WriteString("rule " + rule.name)
		}
	}
	pe := &parserError{Inner: err, prefix: buf.String()}
	p.errs.add(pe)
}

// read advances the parser to the next rune.
func (p *parser) read() {
	p.pt.offset += p.pt.w
	rn, n := utf8.DecodeRune(p.data[p.pt.offset:])
	p.pt.rn = rn
	p.pt.w = n
	p.pt.col++
	if rn == '\n' {
		p.pt.line++
		p.pt.col = 0
	}

	if rn == utf8.RuneError {
		if n > 0 {
			p.addErr(errInvalidEncoding)
		}
	}
}

// restore parser position to the savepoint pt.
func (p *parser) restore(pt savepoint) {
	if p.debug {
		defer p.out(p.in("restore"))
	}
	if pt.offset == p.pt.offset {
		return
	}
	p.pt = pt
}

// get the slice of bytes from the savepoint start to the current position.
func (p *parser) sliceFrom(start savepoint) []byte {
	return p.data[start.position.offset:p.pt.position.offset]
}

func (p *parser) getMemoized(node interface{}) (resultTuple, bool) {
	if len(p.memo) == 0 {
		return resultTuple{}, false
	}
	m := p.memo[p.pt.offset]
	if len(m) == 0 {
		return resultTuple{}, false
	}
	res, ok := m[node]
	return res, ok
}

func (p *parser) setMemoized(pt savepoint, node interface{}, tuple resultTuple) {
	if p.memo == nil {
		p.memo = make(map[int]map[interface{}]resultTuple)
	}
	m := p.memo[pt.offset]
	if m == nil {
		m = make(map[interface{}]resultTuple)
		p.memo[pt.offset] = m
	}
	m[node] = tuple
}

func (p *parser) buildRulesTable(g *grammar) {
	p.rules = make(map[string]*rule, len(g.rules))
	for _, r := range g.rules {
		p.rules[r.name] = r
	}
}

func (p *parser) parse(g *grammar) (val interface{}, err error) {
	if len(g.rules) == 0 {
		p.addErr(errNoRule)
		return nil, p.errs.err()
	}

	// TODO : not super critical but this could be generated
	p.buildRulesTable(g)

	if p.recover {
		// panic can be used in action code to stop parsing immediately
		// and return the panic as an error.
		defer func() {
			if e := recover(); e != nil {
				if p.debug {
					defer p.out(p.in("panic handler"))
				}
				val = nil
				switch e := e.(type) {
				case error:
					p.addErr(e)
				default:
					p.addErr(fmt.Errorf("%v", e))
				}
				err = p.errs.err()
			}
		}()
	}

	// start rule is rule [0]
	p.read() // advance to first rune
	val, ok := p.parseRule(g.rules[0])
	if !ok {
		if len(*p.errs) == 0 {
			// make sure this doesn't go out silently
			p.addErr(errNoMatch)
		}
		return nil, p.errs.err()
	}
	return val, p.errs.err()
}

func (p *parser) parseRule(rule *rule) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseRule " + rule.name))
	}

	if p.memoize {
		res, ok := p.getMemoized(rule)
		if ok {
			p.restore(res.end)
			return res.v, res.b
		}
	}

	start := p.pt
	p.rstack = append(p.rstack, rule)
	p.pushV()
	val, ok := p.parseExpr(rule.expr)
	p.popV()
	p.rstack = p.rstack[:len(p.rstack)-1]
	if ok && p.debug {
		p.print(strings.Repeat(" ", p.depth)+"MATCH", string(p.sliceFrom(start)))
	}

	if p.memoize {
		p.setMemoized(start, rule, resultTuple{val, ok, p.pt})
	}
	return val, ok
}

func (p *parser) parseExpr(expr interface{}) (interface{}, bool) {
	var pt savepoint
	var ok bool

	if p.memoize {
		res, ok := p.getMemoized(expr)
		if ok {
			p.restore(res.end)
			return res.v, res.b
		}
		pt = p.pt
	}

	p.exprCnt++
	var val interface{}
	switch expr := expr.(type) {
	case *actionExpr:
		val, ok = p.parseActionExpr(expr)
	case *andCodeExpr:
		val, ok = p.parseAndCodeExpr(expr)
	case *andExpr:
		val, ok = p.parseAndExpr(expr)
	case *anyMatcher:
		val, ok = p.parseAnyMatcher(expr)
	case *charClassMatcher:
		val, ok = p.parseCharClassMatcher(expr)
	case *choiceExpr:
		val, ok = p.parseChoiceExpr(expr)
	case *labeledExpr:
		val, ok = p.parseLabeledExpr(expr)
	case *litMatcher:
		val, ok = p.parseLitMatcher(expr)
	case *notCodeExpr:
		val, ok = p.parseNotCodeExpr(expr)
	case *notExpr:
		val, ok = p.parseNotExpr(expr)
	case *oneOrMoreExpr:
		val, ok = p.parseOneOrMoreExpr(expr)
	case *ruleRefExpr:
		val, ok = p.parseRuleRefExpr(expr)
	case *seqExpr:
		val, ok = p.parseSeqExpr(expr)
	case *zeroOrMoreExpr:
		val, ok = p.parseZeroOrMoreExpr(expr)
	case *zeroOrOneExpr:
		val, ok = p.parseZeroOrOneExpr(expr)
	default:
		panic(fmt.Sprintf("unknown expression type %T", expr))
	}
	if p.memoize {
		p.setMemoized(pt, expr, resultTuple{val, ok, p.pt})
	}
	return val, ok
}

func (p *parser) parseActionExpr(act *actionExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseActionExpr"))
	}

	start := p.pt
	val, ok := p.parseExpr(act.expr)
	if ok {
		p.cur.pos = start.position
		p.cur.text = p.sliceFrom(start)
		actVal, err := act.run(p)
		if err != nil {
			p.addErrAt(err, start.position)
		}
		val = actVal
	}
	if ok && p.debug {
		p.print(strings.Repeat(" ", p.depth)+"MATCH", string(p.sliceFrom(start)))
	}
	return val, ok
}

func (p *parser) parseAndCodeExpr(and *andCodeExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseAndCodeExpr"))
	}

	ok, err := and.run(p)
	if err != nil {
		p.addErr(err)
	}
	return nil, ok
}

func (p *parser) parseAndExpr(and *andExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseAndExpr"))
	}

	pt := p.pt
	p.pushV()
	_, ok := p.parseExpr(and.expr)
	p.popV()
	p.restore(pt)
	return nil, ok
}

func (p *parser) parseAnyMatcher(any *anyMatcher) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseAnyMatcher"))
	}

	if p.pt.rn != utf8.RuneError {
		start := p.pt
		p.read()
		return p.sliceFrom(start), true
	}
	return nil, false
}

func (p *parser) parseCharClassMatcher(chr *charClassMatcher) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseCharClassMatcher"))
	}

	cur := p.pt.rn
	// can't match EOF
	if cur == utf8.RuneError {
		return nil, false
	}
	start := p.pt
	if chr.ignoreCase {
		cur = unicode.ToLower(cur)
	}

	// try to match in the list of available chars
	for _, rn := range chr.chars {
		if rn == cur {
			if chr.inverted {
				return nil, false
			}
			p.read()
			return p.sliceFrom(start), true
		}
	}

	// try to match in the list of ranges
	for i := 0; i < len(chr.ranges); i += 2 {
		if cur >= chr.ranges[i] && cur <= chr.ranges[i+1] {
			if chr.inverted {
				return nil, false
			}
			p.read()
			return p.sliceFrom(start), true
		}
	}

	// try to match in the list of Unicode classes
	for _, cl := range chr.classes {
		if unicode.Is(cl, cur) {
			if chr.inverted {
				return nil, false
			}
			p.read()
			return p.sliceFrom(start), true
		}
	}

	if chr.inverted {
		p.read()
		return p.sliceFrom(start), true
	}
	return nil, false
}

func (p *parser) parseChoiceExpr(ch *choiceExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseChoiceExpr"))
	}

	for _, alt := range ch.alternatives {
		p.pushV()
		val, ok := p.parseExpr(alt)
		p.popV()
		if ok {
			return val, ok
		}
	}
	return nil, false
}

func (p *parser) parseLabeledExpr(lab *labeledExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseLabeledExpr"))
	}

	p.pushV()
	val, ok := p.parseExpr(lab.expr)
	p.popV()
	if ok && lab.label != "" {
		m := p.vstack[len(p.vstack)-1]
		m[lab.label] = val
	}
	return val, ok
}

func (p *parser) parseLitMatcher(lit *litMatcher) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseLitMatcher"))
	}

	start := p.pt
	for _, want := range lit.val {
		cur := p.pt.rn
		if lit.ignoreCase {
			cur = unicode.ToLower(cur)
		}
		if cur != want {
			p.restore(start)
			return nil, false
		}
		p.read()
	}
	return p.sliceFrom(start), true
}

func (p *parser) parseNotCodeExpr(not *notCodeExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseNotCodeExpr"))
	}

	ok, err := not.run(p)
	if err != nil {
		p.addErr(err)
	}
	return nil, !ok
}

func (p *parser) parseNotExpr(not *notExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseNotExpr"))
	}

	pt := p.pt
	p.pushV()
	_, ok := p.parseExpr(not.expr)
	p.popV()
	p.restore(pt)
	return nil, !ok
}

func (p *parser) parseOneOrMoreExpr(expr *oneOrMoreExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseOneOrMoreExpr"))
	}

	var vals []interface{}

	for {
		p.pushV()
		val, ok := p.parseExpr(expr.expr)
		p.popV()
		if !ok {
			if len(vals) == 0 {
				// did not match once, no match
				return nil, false
			}
			return vals, true
		}
		vals = append(vals, val)
	}
}

func (p *parser) parseRuleRefExpr(ref *ruleRefExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseRuleRefExpr " + ref.name))
	}

	if ref.name == "" {
		panic(fmt.Sprintf("%s: invalid rule: missing name", ref.pos))
	}

	rule := p.rules[ref.name]
	if rule == nil {
		p.addErr(fmt.Errorf("undefined rule: %s", ref.name))
		return nil, false
	}
	return p.parseRule(rule)
}

func (p *parser) parseSeqExpr(seq *seqExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseSeqExpr"))
	}

	var vals []interface{}

	pt := p.pt
	for _, expr := range seq.exprs {
		val, ok := p.parseExpr(expr)
		if !ok {
			p.restore(pt)
			return nil, false
		}
		vals = append(vals, val)
	}
	return vals, true
}

func (p *parser) parseZeroOrMoreExpr(expr *zeroOrMoreExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseZeroOrMoreExpr"))
	}

	var vals []interface{}

	for {
		p.pushV()
		val, ok := p.parseExpr(expr.expr)
		p.popV()
		if !ok {
			return vals, true
		}
		vals = append(vals, val)
	}
}

func (p *parser) parseZeroOrOneExpr(expr *zeroOrOneExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseZeroOrOneExpr"))
	}

	p.pushV()
	val, _ := p.parseExpr(expr.expr)
	p.popV()
	// whether it matched or not, consider it a match
	return val, true
}

func rangeTable(class string) *unicode.RangeTable {
	if rt, ok := unicode.Categories[class]; ok {
		return rt
	}
	if rt, ok := unicode.Properties[class]; ok {
		return rt
	}
	if rt, ok := unicode.Scripts[class]; ok {
		return rt
	}

	// cannot happen
	panic(fmt.Sprintf("invalid Unicode class: %s", class))
}
